#%RAML 1.0 DataType

  type: object
  additionalProperties: false
  properties:
    APDocumentDescription:
      required: true
      type: string
      example: "11111-1111-1111-US100000"
      maxLength: 100
    ARDocumentDateTime:
      description: # Date Time in YYYY-MM-DDThh:mm:ssZ Format
      type: datetime
      example: "2025-12-16T16:00:00+05:30" 
    correlationId:
      type: string
      #pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
      example: "d8a1c5f4-934d-4a3d-8fb8-29ac9b92cf30"
      maxLength: 36
    tigerBillingRequest:
      required: true
      type: string
      example: "10000000000001"
      maxLength: 15