#%RAML 1.0 Trait

headers:
  authorization:
    description: Bearer <JWT token>
    type: string
    required: true
    example: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
responses:
  400:
    description: Token was not provided.
  401:
    description: Bad or expired token. To fix, you should re-authenticate the user.
  403:
    description: The client id validation failed.
  503:
    description: Error communicating with JWKS server.